### ISSUE TITLE
There is no link to documentation on the landing page

### ISSUE THREAD

**Issue by DevJac** [kivy/kivy-website#104]
https://kivy.org/doc/stable/ looks really good. As a newcomer to Kivy I would be encouraged to see that page. Problem is I couldn't find that page. The documentation should be linked to from the landing page (https://kivy.org), but it isn't.

**Comment by janek37** [comment]
As a potential newcomer, this whole project seems really unfriendly. This issue is very old! Is it so hard?

**Comment by janek37** [comment]
The related PR was reverted because 'Documentation' was to long and the menu got pushed down under the slides and it was not visible. There are two solutions:

- use Docs instead of Documentation

- reduce `#logo` width in kivy.css (currently it's 300 px which is much more than needed)

**Comment by DevTown** [comment]
Forgot for this over the last year. I will try to fix it.
