### ISSUE TITLE
HelloWorld Example Incomplete.

### ISSUE THREAD

**Issue by psytron** [kivy/kivy-website#112]
For people expecting to create apps for the various OS platforms ( e.g. MacOS , Android, etc. )
HelloWorld  usage example is incomplete. Example does not demonstrate how to use Kivy to create an app for any of those platforms. 

It would be great to make the usage example complete with regards to achieving Kivy's stated objective. Perhaps even a link to the HelloWorld/TestApp. Showing complete process to get going on example platform.  Even a link to: https://kivy.org/doc/stable/gettingstarted/packaging.html  would make sense, but all the examples on this page are a bit more complex than original HelloWorld usage example.

**Comment by Julian-O** [comment]
The HelloWorld example is how to use the Kivy framework. 

Pushing the complexity of Buildozer etc at that early stage is likely to make it far too complicated.

Given there has been no interest in this for 4 years, I am closing as stale, but if tyou think this is in error, please let us know.
