### ISSUE TITLE
Some places say using Python3 for iOS is not supported, others say otherwise.

### ISSUE THREAD

**Issue by poikilos** [kivy/kivy-website#115]
- [ ] https://kivy.org/doc/stable/faq.html says, "be aware that while Kivy will run in Python 3.4+, our iOS build tools still require Python 2.7"
- [ ] https://kivy.org/doc/stable/guide/packaging-ios.html says, "Currently, packages for iOS can only be generated with Python 2.7. Python 3.4+ support is on the way."

Should the above pages be changed?

The following seem to contradict the information above:
- The kivy-ios project says, "You can select between Python 2.7 or Python 3.7 by specifying the recipes python2 or python3 when building."
- Installing the Python2.7 version via python3 -m virtualenv -p python2.7 ~/kivy_venv has a warning that says, "The Kivy release after 1.11.0 will not support Python 2 anymore" and it it installs a version (1.11.1) after that release.

**Comment by matham** [comment]
Fixed in https://github.com/kivy/kivy/pull/7288. Thanks for the report.
