### ISSUE TITLE
Installation on Linux page shows merge conflict markers

### ISSUE THREAD

**Issue by ygingras** [kivy/kivy-website#126]
This page on the live website has merge conflict markers scatters throughout the text:
https://kivy.org/doc/stable/installation/installation-linux.html

Ex.: 

    Using software packages (PPA etc.)
    
    Ubuntu / Kubuntu / Xubuntu / Lubuntu (Saucy and above) <<<<<<< HEAD     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ======= ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ >>>>>>> master

    1. Add one of the PPAs as you prefer

Note the "HEAD" and "master" sections with the "<<<<<<<" and ">>>>>>>" delimiters.

**Comment by misl6** [comment]
The issue doesn't persists anymore. Feel free to re-open if a fix is still needed :)
