### ISSUE TITLE
Website certificate for kivy.org has expired

### ISSUE THREAD

**Issue by Lauszus** [kivy/kivy-website#129]
The certificate for kivy.org has expired. When visiting the page I get the following error:

![kivy org](https://user-images.githubusercontent.com/1098847/139605946-b3a52005-0c12-404a-baf3-4875a8ba5ce1.png)

**Comment by misl6** [comment]
Fixed it! Thank you for noticing it.

**Comment by Dave-Ortega** [comment]
Yet again today

**Comment by misl6** [comment]
Fixed earlier this morning (~ 0900 CET), is still an issue?

**Comment by Dave-Ortega** [comment]
LGTM!
