### ISSUE TITLE
SSL certification - NET::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by lukasloetkolben** [kivy/kivy-website#136]
Hi,
the kivy.org website is not accessible.

**Comment by fixing-it** [comment]
try using another browser that allows ignoring the certificate warning. Helps until they update the certificate

**Comment by tshirtman** [comment]
The certificate has been renewed, thanks for notifying, sorry about that!

**Comment by unton83** [comment]
Again!
