### ISSUE TITLE
kivy.org is down

### ISSUE THREAD

**Issue by Lauszus** [kivy/kivy-website#141]
There is a connection timeout when trying to visit kivy.org

**Comment by tshirtman** [comment]
Yes, sorry about that, we are aware and trying to resolve the situation with the provider, this will probably last until tomorrow.

**Comment by Lauszus** [comment]
Thanks. I'll use you the backup on readthedocs for now then :)

**Comment by misl6** [comment]
`www.kivy.org` is back online!
