### ISSUE TITLE
kivy.org certificate expired... yet again *sigh*

### ISSUE THREAD

**Issue by leycec** [kivy/kivy-website#146]
It's [two years ago all over again](https://github.com/kivy/kivy-website/issues/129). As further confirmation that we are all living in a time loop until we get it right, the SSL cert for kivy.org appears to have accidentally fallen down the stairs again:

> Did Not Connect: Potential Security Issue

> Firefox detected an issue and did not continue to kivy.org. The website is either misconfigured or your computer clock is set to the wrong time.

> It’s likely the website’s certificate is expired, which prevents Firefox from connecting securely.

> What can you do about it?

> kivy.org has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

> The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.

> Websites prove their identity via certificates, which are valid for a set time period. **The certificate for kivy.org expired on 4/21/2023.**
 
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

Blessed Kivy documentation. Only too late do I now realize I desperately need you. Come back to me, Kivy docs! Come *baaaaaaack*! :sob:

**Comment by misl6** [comment]
> Blessed Kivy documentation. Only too late do I now realize I desperately need you. Come back to me, Kivy docs! Come baaaaaaack! 😭

Glad that someone reads the docs! ❤️ (the cert has been renewed meanwhile)
