### ISSUE TITLE
Can't connect to Kivy website due to expired certificate.

### ISSUE THREAD

**Issue by Sumit112192** [kivy/kivy-website#152]
I was able to access the website yesterday, but today it shows that the certificate has expired, and I can't access it.

The error screen:
![Screenshot from 2023-07-22 11-36-45](https://github.com/kivy/kivy-website/assets/53135486/6f93e69f-c474-4ff5-8dee-818fc810c29d)

**Comment by misl6** [comment]
Thank you for the heads up!
We're back online.
