### ISSUE TITLE
Kivy.org site privacy error, Certificate Expired?

### ISSUE THREAD

**Issue by ElliotGarbus** [kivy/kivy-website#167]
Attempting to access kivy.org results in a warning: 
NET::ERR_CERT_DATE_INVALID
Subject: kivy.org

Issuer: ZeroSSL RSA Domain Secure Site CA

Expires on: Jul 19, 2024

Current date: Jul 20, 2024

![image](https://github.com/user-attachments/assets/84145fa5-ed59-4450-bbed-99763638c92e)

**Comment by misl6** [comment]
Fixed. Thank you!
