### ISSUE TITLE
Outdated IRC logging page and docs

### ISSUE THREAD

**Issue by brousch** [kivy/kivy-website#17]
The Kivy website has an IRC logging page at http://kivy.org/irclogs but IRC logs are now at https://botbot.me/freenode/kivy/ .
##

**Comment by tito** [comment]
But i like it, it wasn't that bad :).

Ok removing it.

**Comment by dessant** [comment]
Here are some more leftovers from 2012 and 2013: http://kivy.org/docs/guide/?C=M;O=A
Some of them come up in dominant places in google search results.

**Comment by dessant** [comment]
Everything fixed.
