### ISSUE TITLE
Broken Fedora Download Links

### ISSUE THREAD

**Issue by ScriptGadget** [kivy/kivy-website#53]
The links for fedora repos on the page at http://kivy.org/#download seem to be broken?
There are no directories for 16,17 or 18 in: http://download.opensuse.org/repositories/home:/thopiekar:/kivy/

I do see a Fedora_20 directory and some CentOS and RHEL directories that might be nice to show on the download page as if they are ready for use.
##

**Comment by dessant** [comment]
@thopiekar ping.

**Comment by dessant** [comment]
This issue was moved to kivy/kivy#4766
