### ISSUE TITLE
Incorrect 3.4 mirror links on Downloads page

### ISSUE THREAD

**Issue by NoiSek** [kivy/kivy-website#58]
Mirror links on the [Download page](http://kivy.org/#download) on kivy.org for version 3.4 link to their respective 2.7 releases instead of the correct 3.4 versions.

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy-website/commit/cd262b6e0ecaff405558f7cdc47abc69e8e22fd5.
