### ISSUE TITLE
Quickstart confusing trying to find out version on Mac

### ISSUE THREAD

**Issue by songproducer** [kivy/kivy-website#66]
https://kivy.org/docs/guide/basic.html#quickstart

In the example of a minimal application there is:

kivy.require('1.0.6') # replace with your current kivy version !

I tried to find out by running kivy --version

but I am dropped into a python shell instead. Trying to find out which version Kivy I downloaded has been difficult.
##

**Comment by dessant** [comment]
The require call can be omitted, and it only fails if the version is older, it does not have to be an exact match.
Your current version is visible in the logs, and depending on how you installed, during installation time.
