### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by hackalog** [kivy/kivy-website#72]
The FAQ should likely note the Python 3.5/Windows compatibility issues under the
"Does Kivy support Python 3.x" question.

e.g. (stealing text from the windows installation page:)

"Python 3.5 is currently not supported on Windows due to issues with MinGW and Python 3.5. Support is not expected for some time. See (http://bugs.python.org/issue4709) for details."

**Comment by dessant** [comment]
There is pr which makes py3.5 msvc builds possible: https://github.com/kivy/kivy/pull/4385. As you noted, the installation docs already cover the temporary limitation, and it seems the fix may land in master in the near future.

**Comment by hackalog** [comment]
Is that the right PR you linked to? (refactor OpenGL implementation?). It doesn't mention MSVC...

**Comment by dessant** [comment]
Yes, the pr has a bigger scope, and it includes fixes related to py3.5 builds.
