### ISSUE TITLE
[Request] SVG logo

### ISSUE THREAD

**Issue by JimiC** [kivy/kivy-website#84]
We like to support `kivy` file icon on `Visual Studio Code` via our [vscode-icons](https://github.com/vscode-icons/vscode-icons/issues/1251) extension.
Is there an `SVG` version of the logo somewhere and if not can we get our hands on one?

Thanks in advance.

**Comment by dessant** [comment]
These are the SVGs of the main shape: https://github.com/kivy/kivy-design/tree/master/logo/svg.
If you'd like to experiment with the circular version of the logo, the Illustrator source is also in the repository.

**Comment by JimiC** [comment]
Great!. Sorry for opening an issue. I missed that repo on my search.

**Comment by dessant** [comment]
NP, we're happy to help. 😋
